name: Exemplo de Output
on: [push]

jobs:
  exemplo1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Gerar uma saida
        id: gerar
        run: |
          echo "valor_teste=Ola do step 1" >> $GITHUB_OUTPUT
          echo "numero=$((1 + 1))" >> $GITHUB_OUTPUT
          echo "data_inicio=$(date)" >> $GITHUB_OUTPUT
      - name: Step 2 - LEr a saida do step anterior
        run: |
          echo "Mensagem: ${{steps.gerar.outputs.valor_teste}}"

