name: Hello Actions
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo "OlÃ¡, GH actions" 



# * * * * * UTC 
# 09-00am  ->> 0 9 * * * 
# A Cada 6 horas ->> 0 */6 * * *  
# A Cada 15 Minutos -> */15 * * * * 
# toda segunda meia noite => 0 0 * * 1
# dia 1 de cada mes as 3 -> 0 3 1 * * 
# Todo dia as 9 e 17 -0> 0 9,17 * * *  